openapi: 3.0.0
info:
  title: backend service
  description: Сервис для управления подписками
  version: 1.0.0

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string

    Subscription:
      type: object
      properties:
        name:
          type: string
        cost:
          type: integer
        id:
          type: string
          format: uuid
        dateStart:
          type: string
          format: date
          example: "2025-07-01"
        dateEnd:
          type: string
          format: date
          example: "2025-07-01"
      required: [name, cost, id, dateStart]

    TotalCostResponse:
      type: object
      properties:
        totalCost:
          type: integer

paths:
  /subscriptions:
    post:
      summary: Создание новой подписки
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '201':
          description: Подписка создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Получение списка подписок
      parameters:
        - name: id
          in: query
          description: ID пользователя
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Список подписок пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Обновление подписки
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '200':
          description: Подписка обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Удаление подписки
      parameters:
        - name: id
          in: query
          description: ID пользователя
          required: false
          schema:
            type: string
            format: uuid
        - name: name
          in: query
          description: Название подписки
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Подписка удалена
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /subscriptions/total_cost:
    get:
      summary: Подсчёт суммарной стоимости подписок за период
      parameters:
        - name: id
          in: query
          required: false
          schema:
            type: string
            format: uuid
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
            example: "2025-07-01"
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
            example: "2025-07-01"

      responses:
        '200':
          description: Суммарная стоимость подписок
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TotalCostResponse'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
